//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaymanProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogrenciler
    {
        public int OgrnId { get; set; }
        public string OgrnAd { get; set; }
        public Nullable<int> OgrnBolum { get; set; }
        public string OgrnIban { get; set; }
        public string OgrnTc { get; set; }
        public Nullable<int> OkulId { get; set; }
    }
}
