//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaymanProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogretmenler
    {
        public int OgretId { get; set; }
        public string OgretAd { get; set; }
        public Nullable<int> BransId { get; set; }
        public string OgretIban { get; set; }
        public string OgretTc { get; set; }
        public Nullable<int> OkulId { get; set; }
    }
}
