//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaymanProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class okul
    {
        public int OkulId { get; set; }
        public string OkulAdi { get; set; }
        public string OkulAdres { get; set; }
        public string OkulVergi { get; set; }
        public string OkulEmail { get; set; }
        public Nullable<int> OkulTuru { get; set; }
        public Nullable<int> IliId { get; set; }
        public Nullable<int> IlcesiId { get; set; }
    }
}
